version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: yarn
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      pucjjxMUCSA1sE+v40uESW/uU/Ff0dH3g4h8pJpgcFNYCvSTd0fwe4lN1bUboErWnCPZfh25eKSA++EIyajiWFVXAchqzF7qemGbULgehvYnVrqWMAZYSKCd7LK2XhVXACn6aXJxsMA8fkoOSm+2hjmo4pD95jeEYkbb+8f8wE282r4tHfLhZBABujXdbNylOkcwgO/AWqa39E7oTPcKYXCnRT/7pR5U8ebK0gPD+Y8+ve61I0s9ZS2OM6EhMof3iNtxCfxq8LzSL1R4w7G/EZpn9C/gow9lHq+eR1HzFA6TQtNa9Ck9wF2C8wiqNFbfOGjwIO/6/VdAXtEXV8hq4h4iENNykJ3KESbabYmiMtmrxh1tMVO29TKeHJpZ4Ht0NDDQr0xRC1cb+3naAZ49H3YkYqxw4jy+3X4+CezCVDOvgUOkYjoe1+qokUbw1FrThaeVPEa5EAtd5vQ8x41+glSpp8ldz8W6F0Sr7uK01HFEPlu4eXOOHrK1UgXl6HzVgNrP60Eb9ZelRtoiN5MGVviliBT3BR1cVN7M8gmdb636vziRrvboArBl0F6nI/pkpeatXkoBrg96HzKlUoQz+rtu6LbZJuBUZ/HzYhSH+JcziM9o/tslehiSGQ5h/OEv8Gq1gXWTrRwpBwXUHE7yanvDvBlXxCh64/kTFx8zLEg=
