sudo: false
language: node_js
node_js:
- '8'
- '10'
- '12'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/surge.bash)"
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: qr13BSUk8cxwJI++EAtbzMsaP0VTJtiLBTAgjE1xcH1+mecxHbu118L4ThWtNq9RBiHbOg3RzrxdGwIJ7ONt3lIUyAiQU/6Zl7B1mE1am9Qcv9OUzpvCWG6UfNPNOnx9yxqwZLgmCpMTXU86A6o3TP1oZoCT4oISrfa3Zrf2NHnLZ3ves+1UCPopBvTKUV+h7pf/4NZU89jz/dpLE5CwWqUzw/ipNRhFI5YMPJoXEWOE+WLHNZpimFG/pvxnutrr1Lm4y8nHfScCoAHdd0JAGp4mMCPnUrw+iZfi5ePTr3jtPApF1kLE3iSYKE9kU2M0p8ErrP6XS9qyiLoz5nqLKdOuWI+GOOjWkJCzkyR4NfWFXTLNgFRwGJiL/LafMNdIbf2KYxTvTxOgUtOdsrfcsnDmB/0jwmrC24S9zZYwp4y8oQECuH/BL0PAMlsVhG+uaEaxMK1JqlXOPUsfrBP0e8j6Qf+fqgyoR8pveU0+Ct+jBIvZdx/rj/REPRFV6k6T8LqAp5WUtpQpmanr7S4Qhj4y06ZK9uKzQAHmcCUuy3R4gSvxOXNnfo0iDCKSMNcHFLQdNoLjiz4GHSauwCEe8Bg9dAp9I+1rEwnLf4r9oTQ9+OQxOAeTnzk3ONoZvofhaBx5Eh6JMysi8BuylP9S/iG/RjDOMwPzxnxoy2RBnKk=
